{% set name = "weave" %}
{% set version = "0.16.0" %}
{% set sha256 = "1a3ee3d018c41e92ac0927f169116089524162992fb4fcf8832cba4a5019d54a" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [py3k]
  script: python setup.py install --record record.txt

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - numpy
    - bsddb  # [not win]

test:
  imports:
    - weave
  commands:
    - python -c "import weave;assert weave.inline('int x=42; return_val=x;') == 42"

about:
  home: https://pypi.python.org/pypi/weave
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Weave: a C++ compiler for Python.'
  description: |
    Weave provides tools for including C/C++ code within Python code. Inlining
    C/C++ code within Python generally results in speedups of 1.5x to 30x over
    algorithms written in pure Python.
    Weave is the stand-alone version of the deprecated Scipy submodule
    ``scipy.weave``.   It is Python 2.x only, and is provided for users that need
    new versions of Scipy (from which the ``weave`` submodule may be removed) but
    have existing code that still depends on ``scipy.weave``.  For new code, users
    are recommended to use Cython.
  dev_url: http://www.github.com/scipy/weave

extra:
  recipe-maintainers:
    - mstimberg
