{% set name = "weave" %}
{% set version = "0.51.32" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ba34a2ea9743b3611ef7ddb73721e84a31eef43c9d811e81960ca2f4b68d67c

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - pydantic >=2.0.0
    - wandb >=0.17.1
    - packaging >=21.0
    - tenacity >=8.3.0,!=8.4.0
    - emoji >=2.12.1
    - uuid-utils >=0.9.0
    - numpy >1.21.0
    - rich
    - gql-with-aiohttp
    - jsonschema >=4.23.0


test:
  # tests from github require modules we don't have, like 'clickhouse_connect',
  # so we can't use them yet
  imports:
    - weave
  commands:
    - pip check
    - weave --help
  requires:
    - pip

about:
  home: https://pypi.python.org/pypi/weave
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Weave: a C++ compiler for Python.'
  description: |
    Weave provides tools for including C/C++ code within Python code. Inlining
    C/C++ code within Python generally results in speedups of 1.5x to 30x over
    algorithms written in pure Python.
    Weave is the stand-alone version of the deprecated Scipy submodule
    ``scipy.weave``.   It is Python 2.x only, and is provided for users that need
    new versions of Scipy (from which the ``weave`` submodule may be removed) but
    have existing code that still depends on ``scipy.weave``.  For new code, users
    are recommended to use Cython.
  dev_url: http://www.github.com/scipy/weave

extra:
  recipe-maintainers:
    - mstimberg
