travis:
  secure:
    BINSTAR_TOKEN: qfJ3+ZpuZalgf9MdiGAUAH9q/CWroJuLNMOQ9ILVjSzLO0i0krF7CFjePanQAQNE3m8geiqJpcbjeO5hg9NWiDS81xtmcvX89A9i8/RsC36z8H49nXgDNDiyYVh+N4MGBNN4syNy51uor3Y8VFvrvVOIfx9T4hVr9wcTbTTEp5ZDbMZjKMjIJW1mRR9A7vlBc5mu/bZHY4rJRNwsnpGb8nGlsZVWGyE5vtv631cyqZYgQYMAfjz1JyRJYIdAoVvOOnhu5BewKUBQWUNmCv/oubA/ijxUeUCZgmxvlGK4RNYDmyUItFpNWPYpPRcowJFbFFfKelK0YJ12nm38bdBP8iycy0oQL9BSAmkn3VM65SDsPt/5iZF+022Tv+AvkZ8HRUSm6CkZgOTF9eJtqf+/Ck+ALyJhIDcy2r/8aImpgaMVsJhwlsJIW9Hi5LS3l66ZNqH6nDtfqhpT0XUujGuAIOlHzpMN4WN6njEsJKzj9+4+1HDBu3wJgNerjqk9sU9XKhL1BtK8wetzoxY3q8mxS7UJsQagbt5ct+dIoM+Jm/2HFwYuLBvWWw/BtgZL13oDPaLT6Ezt1/jYycRnueb5X6oELPDqZ/uLWdmJRXJRs3BbhWOJauKW7MS9qZXfEYD3cb7yuYRbQv9IqpWrIDVrqp6bP+lj4wToLnZqZTb4MEk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
