travis:
  secure:
    BINSTAR_TOKEN: FkudDLu/d/4SBCp9vAu6e55kiWSC90f/TZ+hPaAmD2TaE6sInoA75nnIOLaUm6hCHs/CM9rvLkFhJ3ykhqGGz+k/O0n0o4rga3FzG77aFC2+NAE29z3e30n0ovnPCp3qrMctj61A9yb5jA88Ekin2j93PUwvlvlVwUAkfGquy91RMQ7Kzy5mWfYpJo/6m1YIMNLknKUCPm6DoDDi2uFT3OYE4KuMv6qb2v0jzzCNSstxq7AqoQNY0UOzSRVQt5psoKkyFSzpZfBB39pZ3diZsg/kEXuneX2EupE/VbwJo106TAcP51j9ctO4CtiRj9CIP2HTtOPMDxmw4e/XbOJ0krkg8rAqYaCv0ZjD7NPXySTxnXqmk/395AVfDJg/8MCfxJJ85HI3ztu5KS+ak8m+/PxBIrJ7/KPcpgzFmcDzfJj6iFqzUnsGW4gYBttp9+ICDlrUa2SHrwcXq1xm0XBSZcyFv3RmZ6cXuwOKpzqbsbq0o4Fac81Oby1d6JFzxsCvdTAdk1gd61oMDKyHmReK7XPAGI/M2OJ8KZ5tVFiT/xzcknn5Nb48xEmiTJuCeHI8qFahwCaz9fCXiIiJ8KmpOLYrM5463TsnmKKWiC4Z5t+Nm7HWAb/OKJTtyjconQzOPRtRdT5d6dKFPzmvGMqzyZi6Rg1knw1XWfzN52ie49A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
