appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: BeKOUFPFj+huKLl0craImy+pDdNmWSr+BCoQwwcU6HO493BnbXco5nH8lJ2p9ZWqXrOeuqG8dknOdNf5cD2Q53Y5YolTVI5/atZawAiSmSYS8PP+zxvAJ0jhkKeJBvYUaYHC+cPtt1d59mfvToCfQ4wdOF+u2YGErLWDbNd1IiaLmZI24afLW2moy7L4GNxDcj/jGWiI5EzF7RzfC5Yr+f3I/jgBw2mKliPrEcbVMEFwPjPOy1BvV0ECh7429VGRyf3gqKFjOLMWS8965iTgLQxnWaTdD5AHP9bdhHj2KrPFqSz79PrpYmnwv++bFtJvn3L3UqBM9SYW2NG0vPAaaHN5GL9dz0UL6yj2JaO9KOqVdXcOIk/GhyaUuCgkl6B1vsSxvOMw+MawT6jYpcGjQC56nMozydpa1pWY6Z3oCQkYnjjQLccVWY4Tf+GzM8cFxStjPm+Rdydnmxef+w7zYdHp5DbWvpSFZ+aHlgQcun7jgy2HCmk2DEAxH6gSj8+q1Yar4bU0icN72XuqAOHAaDceT24bNy3LNgzr8fLW3GALVvFeM8gkn6i19L2E6BivQdwCBciJEUrDCOlV0tDVuB5dHlcxAKSEQj1eWwdNX3OAlLkDaZMhYhTGCu4M1tuUBuHdVAXDhBT6i5Sx8LOailxB61h3L9+91DruUHJi6rY=}
provider:
  win: azure
